name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: anonymousdomain/metrics@master
        with:
          token: ${{ secrets.METRICS }}
          base: header
          use_prebuilt_image: yes
          config_padding: 0, 10 + 8%
          config_timezone: Europe/Paris
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_order: base.header, isocalendar,leetcode,languages
