name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: anonymousdomain/metrics@master
        with:
          token: ${{ secrets.METRICS }}
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          config_order: base.header, isocalendar, languages, stars
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Europe/Paris
          plugin_people: yes
          plugin_people_types: contributors, stargazers, watchers, sponsors
          config_display: rows
